import { grobaxDataService } from './dataAccess';
import { LibraryGeneration, LibraryHandoutContent, HandoutOptionType } from '../types';
import jsPDF from 'jspdf';

export interface GenerateHandoutParams {
  userId: string;
  userEmail?: string;
  userName?: string;
  faculty: string;
  department: string;
  level: string;
  institutionCategory?: string;
  institutionContext?: string;
  course: string;
  topic: string;
  searchQuery?: string;
  handoutOption: HandoutOptionType;
  additionalInstructions?: string;
}

/**
 * Calls the secure server API route to retrieve and generate structured academic handouts.
 */
export async function generateLibraryHandoutApi(params: GenerateHandoutParams): Promise<LibraryHandoutContent> {
  const response = await fetch('/api/library/generate', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(params),
  });

  if (!response.ok) {
    throw new Error(`Server returned HTTP ${response.status}`);
  }

  const result = await response.json();
  if (!result.success || !result.data) {
    throw new Error(result.error || 'Failed to synthesize academic handout');
  }

  return result.data as LibraryHandoutContent;
}

/**
 * Saves a completed or updated generation record into Firestore.
 */
export async function saveLibraryGenerationToFirestore(generation: LibraryGeneration): Promise<void> {
  await grobaxDataService.create('libraryGenerations', generation, generation.id);
}

/**
 * Fetches all library handouts generated by a specific student.
 */
export async function fetchUserLibraryGenerations(userId: string): Promise<LibraryGeneration[]> {
  try {
    return await grobaxDataService.list<LibraryGeneration>('libraryGenerations', {
      where: [['userId', '==', userId]],
      orderBy: [{ field: 'createdAt', direction: 'desc' }],
      useCache: true,
      ttlMs: 30000,
    });
  } catch (err) {
    console.warn('[LibraryService] Firestore query error, falling back to simple query:', err);
    const list = await grobaxDataService.list<LibraryGeneration>('libraryGenerations', {
      where: [['userId', '==', userId]],
    });
    return list.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  }
}

/**
 * Subscribes in real-time to a user's library generations.
 */
export function subscribeUserLibraryGenerations(
  userId: string,
  onUpdate: (generations: LibraryGeneration[]) => void,
  onError?: (error: Error) => void
): () => void {
  return grobaxDataService.subscribe<LibraryGeneration>(
    'libraryGenerations',
    {
      where: [['userId', '==', userId]],
    },
    (results) => {
      const sorted = [...results].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
      onUpdate(sorted);
    },
    onError
  );
}

/**
 * Deletes a generation record from the user's library.
 */
export async function deleteLibraryGenerationFromFirestore(generationId: string): Promise<void> {
  await grobaxDataService.delete('libraryGenerations', generationId);
}

/**
 * Generates and downloads a clean, professional, publication-quality academic PDF handout.
 */
export function exportHandoutToPdf(
  handout: LibraryHandoutContent,
  metadata?: { studentName?: string; institution?: string }
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = margin;

  const checkPageBreak = (neededHeight: number) => {
    if (cursorY + neededHeight > pageHeight - margin - 15) {
      doc.addPage();
      cursorY = margin + 10;
      drawHeaderFooter();
    }
  };

  const drawHeaderFooter = () => {
    const totalPages = doc.internal.pages.length - 1;
    doc.setFontSize(8);
    doc.setTextColor(140, 150, 165);
    doc.text(`GROBAX ACADEMIC LIBRARY — ${handout.course || 'ACADEMIC REPOSITORY'}`, margin, 12);
    doc.text(`Page ${doc.getCurrentPageInfo().pageNumber}`, pageWidth - margin - 15, 12);

    doc.setDrawColor(220, 226, 235);
    doc.setLineWidth(0.3);
    doc.line(margin, 14, pageWidth - margin, 14);

    // Footer
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
    doc.text(`Generated on ${new Date().toLocaleDateString()} via Grobax Academic Learning Platform`, margin, pageHeight - 7);
  };

  // Header Banner
  doc.setFillColor(15, 23, 42); // Slate 900
  doc.roundedRect(margin, cursorY, contentWidth, 38, 3, 3, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text('GROBAX ACADEMIC LIBRARY — COMPREHENSIVE HANDOUT', margin + 8, cursorY + 11);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(
    `FACULTY: ${handout.faculty?.toUpperCase()} | DEPT: ${handout.department?.toUpperCase()} | LEVEL: ${handout.level?.toUpperCase()}`,
    margin + 8,
    cursorY + 19
  );

  doc.setTextColor(56, 189, 248); // Sky blue
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(`COURSE: ${handout.course || handout.courseCode || 'GENERAL STUDIES'}`, margin + 8, cursorY + 28);

  doc.setFontSize(8);
  doc.setTextColor(226, 232, 240);
  const pagesText = handout.totalPagesEstimate
    ? `COMPREHENSIVE TREATISE (~${handout.totalPagesEstimate} PAGES EQUIVALENT)`
    : 'COMPREHENSIVE 15-26 PAGE TREATISE';
  doc.text(pagesText, margin + 8, cursorY + 34);

  cursorY += 46;

  // Handout Title
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  const titleLines = doc.splitTextToSize(handout.title || handout.topic, contentWidth);
  doc.text(titleLines, margin, cursorY);
  cursorY += titleLines.length * 6.5 + 4;

  // Metadata Subtitle / Badges
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Academic Rigor Standard: ${handout.targetAudienceLevel || handout.level} • Publication Date: ${new Date().toLocaleDateString()} • Student: ${metadata?.studentName || 'Scholar'}`,
    margin,
    cursorY
  );
  cursorY += 6;

  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.5);
  doc.line(margin, cursorY, margin + contentWidth, cursorY);
  cursorY += 8;

  // 1. Table of Contents / Curriculum Architecture
  if (handout.tableOfContents && handout.tableOfContents.length > 0) {
    checkPageBreak(35);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(margin, cursorY - 2, contentWidth, Math.min(60, handout.tableOfContents.length * 5.5 + 14), 2, 2, 'F');
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 58, 138); // Blue 900
    doc.text('TABLE OF CONTENTS & CHAPTER SYLLABUS', margin + 4, cursorY + 4);
    cursorY += 9;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);
    handout.tableOfContents.forEach((item, tIdx) => {
      checkPageBreak(8);
      const tocLine = `${tIdx + 1}. ${item}`;
      const splitToc = doc.splitTextToSize(tocLine, contentWidth - 8);
      doc.text(splitToc, margin + 4, cursorY);
      cursorY += splitToc.length * 4.5;
    });
    cursorY += 6;
  }

  // 2. Learning Objectives (Bloom's Taxonomy)
  if (handout.learningObjectives && handout.learningObjectives.length > 0) {
    checkPageBreak(35);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(2, 132, 199);
    doc.text('CORE LEARNING OBJECTIVES & COMPETENCIES', margin, cursorY);
    cursorY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);

    handout.learningObjectives.forEach((obj, idx) => {
      checkPageBreak(10);
      const bulletText = `• [LO-${idx + 1}]: ${obj}`;
      const lines = doc.splitTextToSize(bulletText, contentWidth - 4);
      doc.text(lines, margin + 2, cursorY);
      cursorY += lines.length * 4.5 + 1.5;
    });
    cursorY += 4;
  }

  // 3. Key Concepts
  if (handout.keyConcepts && handout.keyConcepts.length > 0) {
    checkPageBreak(35);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(2, 132, 199);
    doc.text('KEY THEORETICAL & APPLIED PILLARS', margin, cursorY);
    cursorY += 6;

    handout.keyConcepts.forEach((concept) => {
      checkPageBreak(12);
      doc.setFillColor(241, 245, 249);
      doc.roundedRect(margin, cursorY - 3, contentWidth, 8.5, 1.5, 1.5, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(30, 41, 59);
      const lines = doc.splitTextToSize(`✓ ${concept}`, contentWidth - 6);
      doc.text(lines, margin + 3, cursorY + 2.5);
      cursorY += Math.max(8.5, lines.length * 4 + 3) + 2;
    });
    cursorY += 4;
  }

  // 4. Main Exhaustive Chapters & Sections
  if (handout.sections && handout.sections.length > 0) {
    handout.sections.forEach((sec, sIdx) => {
      checkPageBreak(40);
      doc.setFillColor(239, 246, 255); // Blue 50
      doc.roundedRect(margin, cursorY - 2, contentWidth, 9, 1.5, 1.5, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(30, 58, 138); // Blue 900
      const chapterLabel = sec.chapterNumber ? `CHAPTER ${sec.chapterNumber}: ` : `MODULE ${sIdx + 1}: `;
      doc.text(`${chapterLabel}${sec.title}`, margin + 3, cursorY + 4);
      cursorY += 12;

      // Section Body Content
      if (sec.content) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(51, 65, 85);
        const secLines = doc.splitTextToSize(sec.content, contentWidth);
        doc.text(secLines, margin, cursorY);
        cursorY += secLines.length * 4.8 + 4;
      }

      // Key Points
      if (sec.keyPoints && sec.keyPoints.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(71, 85, 105);
        doc.text('Key Mechanics & Rules:', margin + 2, cursorY);
        cursorY += 4.5;

        doc.setFont('helvetica', 'normal');
        sec.keyPoints.forEach((kp) => {
          checkPageBreak(10);
          const kpLines = doc.splitTextToSize(`• ${kp}`, contentWidth - 6);
          doc.text(kpLines, margin + 4, cursorY);
          cursorY += kpLines.length * 4.2 + 1.5;
        });
        cursorY += 3;
      }

      // Formulas (handles both string and HandoutFormulaItem)
      if (sec.formulas && sec.formulas.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(67, 56, 202);
        doc.text('Mathematical & Governing Equations:', margin + 2, cursorY);
        cursorY += 4.5;

        sec.formulas.forEach((formItem) => {
          checkPageBreak(14);
          doc.setFillColor(238, 242, 255); // Indigo 50
          doc.roundedRect(margin + 2, cursorY - 2, contentWidth - 4, 10, 1, 1, 'F');
          
          if (typeof formItem === 'string') {
            doc.setFont('courier', 'bold');
            doc.setFontSize(8.5);
            doc.setTextColor(67, 56, 202);
            doc.text(formItem, margin + 5, cursorY + 3.5);
            cursorY += 12;
          } else {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(8);
            doc.setTextColor(49, 46, 129);
            doc.text(`${formItem.name}:`, margin + 5, cursorY + 2.5);

            doc.setFont('courier', 'bold');
            doc.setFontSize(8.5);
            doc.setTextColor(67, 56, 202);
            doc.text(formItem.expression, margin + 5, cursorY + 6.5);
            cursorY += 13;

            if (formItem.parameters || formItem.application) {
              doc.setFont('helvetica', 'italic');
              doc.setFontSize(7.5);
              doc.setTextColor(100, 116, 139);
              const paramText = `Where: ${formItem.parameters || ''} ${formItem.application ? `| Application: ${formItem.application}` : ''}`;
              const paramLines = doc.splitTextToSize(paramText, contentWidth - 10);
              doc.text(paramLines, margin + 5, cursorY);
              cursorY += paramLines.length * 3.5 + 2;
            }
          }
        });
        cursorY += 2;
      }

      // Calculations / Step-by-Step Derivations
      if (sec.calculations && sec.calculations.length > 0) {
        sec.calculations.forEach((calc, cIdx) => {
          checkPageBreak(25);
          doc.setFillColor(254, 243, 199); // Amber 100
          doc.roundedRect(margin + 2, cursorY - 2, contentWidth - 4, 8, 1, 1, 'F');

          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8.5);
          doc.setTextColor(146, 64, 14); // Amber 800
          doc.text(`📐 Step-by-Step Calculation ${cIdx + 1}: ${calc.title || 'Mathematical Derivation'}`, margin + 5, cursorY + 3);
          cursorY += 10;

          // Problem statement
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(30, 41, 59);
          const probLines = doc.splitTextToSize(`Problem Statement: ${calc.problem}`, contentWidth - 8);
          doc.text(probLines, margin + 4, cursorY);
          cursorY += probLines.length * 4 + 2;

          if (calc.given) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(7.5);
            doc.setTextColor(71, 85, 105);
            doc.text(`Given Parameters: ${calc.given}`, margin + 4, cursorY);
            cursorY += 4.5;
          }

          if (calc.formula) {
            doc.setFont('courier', 'bold');
            doc.setFontSize(8);
            doc.setTextColor(67, 56, 202);
            doc.text(`Formula Applied: ${calc.formula}`, margin + 4, cursorY);
            cursorY += 5;
          }

          // Steps
          if (calc.steps && calc.steps.length > 0) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(8);
            doc.setTextColor(51, 65, 85);
            calc.steps.forEach((step, sNum) => {
              checkPageBreak(8);
              const stepLines = doc.splitTextToSize(`Step ${sNum + 1}: ${step}`, contentWidth - 10);
              doc.text(stepLines, margin + 6, cursorY);
              cursorY += stepLines.length * 3.8 + 1;
            });
            cursorY += 2;
          }

          // Final Solution
          checkPageBreak(12);
          doc.setFillColor(220, 252, 231); // Green 100
          doc.roundedRect(margin + 4, cursorY - 1, contentWidth - 8, 7.5, 1, 1, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(22, 101, 52);
          doc.text(`✓ Final Result: ${calc.solution} ${calc.units ? `[${calc.units}]` : ''}`, margin + 7, cursorY + 4);
          cursorY += 10;
        });
      }

      // Worked Examples (handles string and HandoutWorkedExample)
      if (sec.examples && sec.examples.length > 0) {
        sec.examples.forEach((exItem, eIdx) => {
          checkPageBreak(20);
          if (typeof exItem === 'string') {
            doc.setFillColor(240, 253, 244); // Emerald 50
            doc.roundedRect(margin + 2, cursorY - 2, contentWidth - 4, 10, 1, 1, 'F');
            doc.setFont('helvetica', 'italic');
            doc.setFontSize(8);
            doc.setTextColor(22, 101, 52);
            const exLines = doc.splitTextToSize(`Example ${eIdx + 1}: ${exItem}`, contentWidth - 10);
            doc.text(exLines, margin + 5, cursorY + 2.5);
            cursorY += Math.max(10, exLines.length * 3.8 + 4) + 2;
          } else {
            doc.setFillColor(240, 253, 244);
            doc.roundedRect(margin + 2, cursorY - 2, contentWidth - 4, 8, 1, 1, 'F');
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(8.5);
            doc.setTextColor(22, 101, 52);
            doc.text(`📝 Worked Example: ${exItem.title || 'Case Analysis'}`, margin + 5, cursorY + 3.5);
            cursorY += 10;

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(8);
            doc.setTextColor(51, 65, 85);
            const scenLines = doc.splitTextToSize(`Scenario: ${exItem.scenario}`, contentWidth - 8);
            doc.text(scenLines, margin + 4, cursorY);
            cursorY += scenLines.length * 3.8 + 2;

            if (exItem.stepByStepSolution && exItem.stepByStepSolution.length > 0) {
              exItem.stepByStepSolution.forEach((solStep, solIdx) => {
                checkPageBreak(8);
                const sLines = doc.splitTextToSize(`• Step ${solIdx + 1}: ${solStep}`, contentWidth - 10);
                doc.text(sLines, margin + 6, cursorY);
                cursorY += sLines.length * 3.6 + 1;
              });
              cursorY += 2;
            }

            if (exItem.takeaway) {
              doc.setFont('helvetica', 'bold');
              doc.setFontSize(7.5);
              doc.setTextColor(21, 128, 61);
              doc.text(`Takeaway: ${exItem.takeaway}`, margin + 6, cursorY);
              cursorY += 5;
            }
          }
        });
      }

      // Diagram / Schematic illustration / Academic Plate
      if (sec.diagram || sec.diagramDescription || sec.imageUrl) {
        checkPageBreak(48);
        const figNum = sec.diagram?.figureNumber || sec.figureNumber || `Figure ${(sec.chapterNumber || sIdx + 1)}.1`;
        const diagTitle = sec.diagram?.title || `${sec.title} — System Architecture & Workflow`;
        
        // Outer Plate Frame
        doc.setFillColor(15, 23, 42); // Slate 900
        doc.roundedRect(margin + 2, cursorY - 2, contentWidth - 4, 38, 2, 2, 'F');
        doc.setDrawColor(51, 65, 85);
        doc.setLineWidth(0.5);
        doc.roundedRect(margin + 2, cursorY - 2, contentWidth - 4, 38, 2, 2, 'S');

        // Header
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(56, 189, 248); // Sky blue
        doc.text(`[TEXTBOOK FIGURE PLATE] ${figNum}: ${diagTitle.slice(0, 65)}`, margin + 6, cursorY + 4);

        // Draw 4 visual flow stages inside the PDF plate
        const components = sec.diagram?.keyComponents && sec.diagram.keyComponents.length >= 3
          ? sec.diagram.keyComponents
          : [
              '1. State & Input Intake',
              '2. Core Transformation Engine',
              '3. Constraint Invariants Check',
              '4. Regulated Output Equilibrium',
            ];

        const cardW = (contentWidth - 24) / 4;
        const cardY = cursorY + 7;
        const cardH = 18;

        components.slice(0, 4).forEach((comp, cNum) => {
          const cardX = margin + 6 + cNum * (cardW + 2);
          
          // Card background
          if (cNum === 0) doc.setFillColor(30, 58, 138); // Blue 900
          else if (cNum === 1) doc.setFillColor(3, 105, 161); // Sky 700
          else if (cNum === 2) doc.setFillColor(4, 120, 87); // Emerald 700
          else doc.setFillColor(109, 40, 217); // Purple 700

          doc.roundedRect(cardX, cardY, cardW, cardH, 1, 1, 'F');

          // Stage badge
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(6.5);
          doc.setTextColor(255, 255, 255);
          doc.text(`STAGE ${cNum + 1}`, cardX + 2.5, cardY + 3.8);

          // Component title
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(6);
          doc.setTextColor(241, 245, 249);
          const cLines = doc.splitTextToSize(comp, cardW - 4);
          doc.text(cLines.slice(0, 3), cardX + 2.5, cardY + 7.5);

          // Arrow to next stage
          if (cNum < 3) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(7);
            doc.setTextColor(56, 189, 248);
            doc.text('>', cardX + cardW + 0.3, cardY + 10);
          }
        });

        // Baseline Plate Caption
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(6.8);
        doc.setTextColor(148, 163, 184);
        const captionText = sec.diagram?.imageCaption || sec.imageCaption || sec.diagramDescription || `Figure illustrated in direct reference to ${handout.topic} for examination review.`;
        const capLines = doc.splitTextToSize(`Plate Note: ${captionText}`, contentWidth - 12);
        doc.text(capLines.slice(0, 2), margin + 6, cursorY + 31);

        cursorY += 42;
      }

      // Exam Pitfalls
      if (sec.examPitfalls && sec.examPitfalls.length > 0) {
        checkPageBreak(15);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(185, 28, 28);
        doc.text('⚠️ Common Student Exam Pitfalls & Blunders:', margin + 2, cursorY);
        cursorY += 4;

        sec.examPitfalls.forEach((pitfall) => {
          checkPageBreak(8);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(7.5);
          doc.setTextColor(127, 29, 29);
          const pLines = doc.splitTextToSize(`• ${pitfall}`, contentWidth - 8);
          doc.text(pLines, margin + 5, cursorY);
          cursorY += pLines.length * 3.5 + 1;
        });
        cursorY += 3;
      }

      cursorY += 6;
    });
  }

  // 5. Mastery Multi-Step Calculations Suite
  if (handout.masteryCalculations && handout.masteryCalculations.length > 0) {
    checkPageBreak(40);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(146, 64, 14); // Amber 800
    doc.text('EXHAUSTIVE MASTERY CALCULATIONS & QUANTITATIVE WORKBENCH', margin, cursorY);
    cursorY += 6;

    handout.masteryCalculations.forEach((mCalc, mIdx) => {
      checkPageBreak(25);
      doc.setFillColor(254, 243, 199);
      doc.roundedRect(margin, cursorY - 2, contentWidth, 8, 1, 1, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(146, 64, 14);
      doc.text(`Mastery Problem ${mIdx + 1}: ${mCalc.title}`, margin + 4, cursorY + 3.5);
      cursorY += 10;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(30, 41, 59);
      const mProbLines = doc.splitTextToSize(mCalc.problem, contentWidth - 6);
      doc.text(mProbLines, margin + 3, cursorY);
      cursorY += mProbLines.length * 3.8 + 2;

      if (mCalc.steps && mCalc.steps.length > 0) {
        mCalc.steps.forEach((st, sNum) => {
          checkPageBreak(8);
          const stLines = doc.splitTextToSize(`[Step ${sNum + 1}] ${st}`, contentWidth - 8);
          doc.text(stLines, margin + 5, cursorY);
          cursorY += stLines.length * 3.6 + 1;
        });
        cursorY += 2;
      }

      checkPageBreak(10);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(22, 101, 52);
      doc.text(`Result: ${mCalc.solution} ${mCalc.units ? `[${mCalc.units}]` : ''}`, margin + 5, cursorY);
      cursorY += 7;
    });
    cursorY += 4;
  }

  // 6. Quick Reference Formula Sheet
  if (handout.quickFormulaSheet && handout.quickFormulaSheet.length > 0) {
    checkPageBreak(35);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(67, 56, 202);
    doc.text('COMPREHENSIVE FORMULA & GOVERNING LAWS SHEET', margin, cursorY);
    cursorY += 6;

    handout.quickFormulaSheet.forEach((fSheet) => {
      checkPageBreak(12);
      doc.setFillColor(238, 242, 255);
      doc.roundedRect(margin, cursorY - 2, contentWidth, 8, 1, 1, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(49, 46, 129);
      doc.text(`${fSheet.name}:`, margin + 4, cursorY + 3.5);

      doc.setFont('courier', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(67, 56, 202);
      doc.text(fSheet.expression, margin + 45, cursorY + 3.5);
      cursorY += 10;
    });
    cursorY += 4;
  }

  // 7. Important Terms & Glossary
  if (handout.importantTerms && handout.importantTerms.length > 0) {
    checkPageBreak(35);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(2, 132, 199);
    doc.text('ACADEMIC DEFINITIONS & TERMINOLOGY GLOSSARY', margin, cursorY);
    cursorY += 6;

    handout.importantTerms.forEach((termItem) => {
      checkPageBreak(12);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text(`• ${termItem.term}:`, margin + 2, cursorY);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);
      const defLines = doc.splitTextToSize(`  ${termItem.definition}`, contentWidth - 6);
      doc.text(defLines, margin + 4, cursorY + 4);
      cursorY += defLines.length * 3.8 + 5;
    });
  }

  // 8. Summary & Rapid Revision Notes
  if (handout.summary || (handout.quickRevisionPoints && handout.quickRevisionPoints.length > 0)) {
    checkPageBreak(35);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(2, 132, 199);
    doc.text('SUMMARY & RAPID EXAM REVISION ANCHORS', margin, cursorY);
    cursorY += 6;

    if (handout.summary) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(51, 65, 85);
      const sumLines = doc.splitTextToSize(handout.summary, contentWidth);
      doc.text(sumLines, margin, cursorY);
      cursorY += sumLines.length * 4.5 + 4;
    }

    if (handout.quickRevisionPoints && handout.quickRevisionPoints.length > 0) {
      handout.quickRevisionPoints.forEach((pt) => {
        checkPageBreak(10);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(30, 41, 59);
        const ptLines = doc.splitTextToSize(`⚡ ${pt}`, contentWidth - 4);
        doc.text(ptLines, margin + 2, cursorY);
        cursorY += ptLines.length * 3.8 + 1.5;
      });
      cursorY += 4;
    }
  }

  // 9. Probable Examination Questions with Allocated Marks & Model Schemes
  if (handout.possibleExamQuestions && handout.possibleExamQuestions.length > 0) {
    checkPageBreak(40);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(2, 132, 199);
    doc.text('PROBABLE UNIVERSITY EXAMINATION QUESTIONS & MARKING GUIDES', margin, cursorY);
    cursorY += 6;

    handout.possibleExamQuestions.forEach((qItem, qIdx) => {
      checkPageBreak(22);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      const marksBadge = qItem.marks ? ` [${qItem.marks} Marks]` : '';
      const qLines = doc.splitTextToSize(`Q${qIdx + 1}: ${qItem.question}${marksBadge}`, contentWidth - 4);
      doc.text(qLines, margin + 2, cursorY);
      cursorY += qLines.length * 4 + 2;

      if (qItem.answerGuide) {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139);
        const aLines = doc.splitTextToSize(`Model Answer / Marking Scheme: ${qItem.answerGuide}`, contentWidth - 8);
        doc.text(aLines, margin + 5, cursorY);
        cursorY += aLines.length * 3.5 + 3.5;
      }
    });
    cursorY += 4;
  }

  // 10. References & Academic Citations
  if (handout.references && handout.references.length > 0) {
    checkPageBreak(30);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(2, 132, 199);
    doc.text('RECOMMENDED ACADEMIC TEXTBOOKS & CITATIONS', margin, cursorY);
    cursorY += 6;

    handout.references.forEach((ref, rIdx) => {
      checkPageBreak(10);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(71, 85, 105);
      const refStr = `[${rIdx + 1}] ${ref.title}. ${ref.source || ''} ${ref.year ? `(${ref.year})` : ''}`;
      const refLines = doc.splitTextToSize(refStr, contentWidth - 4);
      doc.text(refLines, margin + 2, cursorY);
      cursorY += refLines.length * 3.5 + 1.5;
    });
  }

  // Final pass: draw header & footer on all pages
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawHeaderFooter();
  }

  // Clean filename
  const cleanTitle = (handout.title || handout.topic || 'Grobax_Academic_Handout')
    .replace(/[^a-zA-Z0-9_-]/g, '_')
    .substring(0, 40);

  doc.save(`${cleanTitle}.pdf`);
}

/**
 * Text-to-speech helper using browser SpeechSynthesis for reading the summary or key points aloud.
 */
export function playHandoutAudioSummary(textToRead: string, onEnd?: () => void): () => void {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
    console.warn('Speech synthesis not supported on this device.');
    return () => {};
  }

  window.speechSynthesis.cancel();

  const utterance = new SpeechSynthesisUtterance(textToRead);
  utterance.rate = 1.0;
  utterance.pitch = 1.0;
  utterance.lang = 'en-US';

  if (onEnd) {
    utterance.onend = onEnd;
    utterance.onerror = onEnd;
  }

  window.speechSynthesis.speak(utterance);

  return () => {
    window.speechSynthesis.cancel();
  };
}
